### ISSUE TITLE
Folder.description type mismatch with v2 collection schema

### ISSUE THREAD

**Issue by gdereese** [postmanlabs/postman-collection#360]
When writing out a Collection object to JSON, the resulting JSON is not valid per the v2 Collection schema.  

The issue is that the JSON output contains Folder.description properties serialized as Description objects (containing content and type properties), while the Folder.description property as defined in the v2 Collection schema accepts only string values.

This presents a problem when trying to use the Postman API to create/update a shared collection.  Since your API is validating the input JSON against the schema, any output generated from postman-collection results in the following response, and the collection cannot be saved:

`{
  "error":
  {
    "name":"malformedRequestError",
    "message":"Data does not match any schemas from \"oneOf\" at item.0"
  }
}`

**Comment by gdereese** [comment]
If you can confirm which datatype for Folder.description is correct (string OR Description object), I can submit a pull request for either:
* fixing postman-collection to use a string for this property OR
* fixing the postman v2 collection schema to specify a Description type for this property

**Comment by czardoz** [comment]
@gdereese Thanks for reporting this! The schema needs to be updated to accept strings as descriptions, which I am doing right away :smile:

**Comment by gdereese** [comment]
Yep, I can see that the latest commit to the schemas addresses this and my collection JSON is now validated by it.  Thanks for the quick turnaround!

When will the Postman API be updated to use this corrected version of the v2 schema so I am able to POST/PUT collections to my account?

**Comment by czardoz** [comment]
We'll be updating those with the next deployment, hopefully in a couple of days. Also, it seems that you're a heavy user of our developer toolchain, and we're working to make it as simple as possible to use. 

If you have any feedback or questions, do feel free to join our [community channel on Slack]( https://www.getpostman.com/slack-invite). You can reach me directly, my username there is the same as my Github username :)

**Comment by gdereese** [comment]
Thanks.  It doesn't yet appear you've updated the schema used for validating by the Postman API.  Any ETA on this?  My work with this is blocked until this is resolved.

**Comment by kunagpal** [comment]
@gdereese This should have been fixed in the latest series of schema changes: http://schema.getpostman.com/json/collection/v2.0.0/docs/index.html.

**Comment by gdereese** [comment]
Indeed, the schema you linked to has the update in question.  However, I still can't currently post a collection to the Postman API.  I double-checked that my JSON is valid against this schema, but it appears the validation used by the API endpoint is still referencing an old version of this schema without this fix, as it seems to go through once I change my Folder.description content back to a string in my request body.

If there's another repo that's more appropriate to log an issue for the schema validation done by the API, I'll gladly move it there, just let me know.
